name: Rust

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  plugin:
    name: Plugin NRO
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
        name: Rust Cache
        with:
          prefix-key: "plugin"
          cache-all-crates: true
      - name: Install Skyline
        run: |
          cargo install cargo-skyline
          cargo-skyline skyline update-std
      - name: Build release NRO
        id: build_release
        run: RUSTFLAGS=-g cargo-skyline skyline build --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-skyline-switch/release/libsmush_info.nro
          tag: ${{ github.ref }}
          overwrite: true
